Information Technology:    XLK
Financials:               XLF
Energy:                   XLE
Health Care:              XLV
Consumer Discretionary:   XLY
Consumer Staples:         XLP
Industrials:              XLI
Materials:                XLB
Utilities:                XLU
Real Estate:              XLRE
Communication Services:   XLC
